version: "3.8"
services:
  rag-qa-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    ports:
      - "8000:8000"
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /workspace
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/workspace
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CROSS_ENCODER_MODEL=cross-encoder/ms-marco-MiniLM-L-6-v2
      - EMBEDDING_PROVIDER=huggingface
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
      - MONGODB_URL=mongodb://admin:secret@mongodb:27017/rag_chat?authSource=admin
      - QDRANT_API_KEY=secret
    networks:
      - rag-shared-network
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    # ports:
    #   - "6333:6333"
    #   - "6334:6334"
    environment:
      - QDRANT__SERVICE__API_KEY=secret
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped
    networks:
      - rag-shared-network

networks:
  rag-shared-network:
    external: true

volumes:
  qdrant_storage:
